vich_uploader:
  db_driver: orm

  mappings:
    article_cover:
      uri_prefix: /assets/images/articles
      upload_destination: "%kernel.project_dir%/public/assets/images/articles" # %kernel.project_dir% = __DIR
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
