index:
   path: /
   controller: App\Controller\DefaultController::index

home:
   path: /home
   controller: App\Controller\HomeController::index

games:
   path: /games
   controller: App\Controller\GamesController::index

# new:
#    path: /games
#    controller: App\Controller\GamesController::index

plateform:
   path: /plateform
   controller: App\Controller\PlateformController::index

category:
   path: /category
   controller: App\Controller\CategoryController::index